// Group behaviors: emergent cooperative actions from social + behavior layers.
//
// Group behaviors arise when multiple creatures of the same faction coordinate
// actions: cooperative hunting (surround prey), territory defense (respond to
// intruders as a group), and resource sharing (trade food for social bonds).

#![allow(dead_code)]

use super::factions::{FactionId, FactionRegistry};
use super::relationships::CreatureId;

/// A group coordination request generated by the social system.
#[derive(Debug, Clone, PartialEq)]
pub enum GroupAction {
    /// Hunt together: faction members converge on prey.
    CooperativeHunt {
        prey_position: [i32; 3],
        participants: Vec<CreatureId>,
    },
    /// Defend territory: faction members move to intercept intruder.
    TerritoryDefense {
        intruder_position: [i32; 3],
        defenders: Vec<CreatureId>,
    },
    /// Share food: one creature gives food to a hungry ally.
    ShareFood {
        giver: CreatureId,
        receiver: CreatureId,
    },
    /// Rally: gather at a point (e.g., for migration or regrouping).
    Rally {
        position: [i32; 3],
        participants: Vec<CreatureId>,
    },
}

/// Information about a creature's current state for group decision-making.
#[derive(Debug, Clone)]
pub struct CreatureState {
    pub id: CreatureId,
    pub position: [i32; 3],
    /// Energy fraction (0.0–1.0).
    pub energy: f32,
    /// Health fraction (0.0–1.0).
    pub health: f32,
    /// Whether currently engaged in combat.
    pub in_combat: bool,
}

/// Plan a cooperative hunt if enough faction members are nearby.
/// `prey_pos`: position of the prey.
/// `members`: all faction members with their states.
/// `min_hunters`: minimum number of hunters to coordinate.
/// `range`: maximum distance from prey to participate.
pub fn plan_cooperative_hunt(
    prey_pos: [i32; 3],
    members: &[CreatureState],
    min_hunters: usize,
    range: f32,
) -> Option<GroupAction> {
    let eligible: Vec<CreatureId> = members
        .iter()
        .filter(|m| {
            !m.in_combat && m.health > 0.3 && position_distance(m.position, prey_pos) <= range
        })
        .map(|m| m.id)
        .collect();

    if eligible.len() >= min_hunters {
        Some(GroupAction::CooperativeHunt {
            prey_position: prey_pos,
            participants: eligible,
        })
    } else {
        None
    }
}

/// Plan territory defense when an intruder is detected.
/// `intruder_pos`: position of the intruder.
/// `chunk_xz`: the chunk the intruder is in.
/// `faction_id`: the defending faction.
/// `members`: faction members with states.
/// `registry`: faction registry (for territory check).
/// `max_defenders`: maximum number of defenders to mobilize.
pub fn plan_territory_defense(
    intruder_pos: [i32; 3],
    chunk_xz: [i32; 2],
    faction_id: FactionId,
    members: &[CreatureState],
    registry: &FactionRegistry,
    max_defenders: usize,
) -> Option<GroupAction> {
    // Only defend if chunk is our territory
    let faction = registry.factions.get(&faction_id)?;
    if !faction.owns_territory(chunk_xz) {
        return None;
    }

    // Pick closest healthy members
    let mut candidates: Vec<&CreatureState> = members
        .iter()
        .filter(|m| !m.in_combat && m.health > 0.4)
        .collect();

    candidates.sort_by(|a, b| {
        let da = position_distance(a.position, intruder_pos);
        let db = position_distance(b.position, intruder_pos);
        da.partial_cmp(&db).unwrap_or(std::cmp::Ordering::Equal)
    });

    let defenders: Vec<CreatureId> = candidates
        .iter()
        .take(max_defenders)
        .map(|c| c.id)
        .collect();

    if defenders.is_empty() {
        return None;
    }

    Some(GroupAction::TerritoryDefense {
        intruder_position: intruder_pos,
        defenders,
    })
}

/// Plan food sharing: find the hungriest ally near a well-fed member.
/// Returns a ShareFood action if a suitable pair is found.
pub fn plan_food_sharing(
    members: &[CreatureState],
    hunger_threshold: f32,
    share_range: f32,
) -> Option<GroupAction> {
    // Find well-fed members (potential givers)
    let givers: Vec<&CreatureState> = members.iter().filter(|m| m.energy > 0.7).collect();

    // Find hungry members (potential receivers)
    let mut receivers: Vec<&CreatureState> = members
        .iter()
        .filter(|m| m.energy < hunger_threshold)
        .collect();

    // Sort receivers by hunger (most hungry first)
    receivers.sort_by(|a, b| {
        a.energy
            .partial_cmp(&b.energy)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    // Find closest giver-receiver pair
    for receiver in &receivers {
        for giver in &givers {
            if giver.id == receiver.id {
                continue;
            }
            if position_distance(giver.position, receiver.position) <= share_range {
                return Some(GroupAction::ShareFood {
                    giver: giver.id,
                    receiver: receiver.id,
                });
            }
        }
    }

    None
}

/// Plan a rally point for scattered faction members.
/// `center`: rally position.
/// `members`: faction members with states.
/// `scatter_threshold`: minimum average distance to trigger rally.
pub fn plan_rally(
    center: [i32; 3],
    members: &[CreatureState],
    scatter_threshold: f32,
) -> Option<GroupAction> {
    if members.is_empty() {
        return None;
    }

    let avg_dist: f32 = members
        .iter()
        .map(|m| position_distance(m.position, center))
        .sum::<f32>()
        / members.len() as f32;

    if avg_dist > scatter_threshold {
        let participants = members.iter().map(|m| m.id).collect();
        Some(GroupAction::Rally {
            position: center,
            participants,
        })
    } else {
        None
    }
}

fn position_distance(a: [i32; 3], b: [i32; 3]) -> f32 {
    let dx = (a[0] - b[0]) as f32;
    let dy = (a[1] - b[1]) as f32;
    let dz = (a[2] - b[2]) as f32;
    (dx * dx + dy * dy + dz * dz).sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::social::factions::Faction;

    fn make_member(id: u64, pos: [i32; 3], energy: f32, health: f32) -> CreatureState {
        CreatureState {
            id: CreatureId(id),
            position: pos,
            energy,
            health,
            in_combat: false,
        }
    }

    #[test]
    fn cooperative_hunt_needs_minimum_hunters() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.8),
        ];
        // Need 3 hunters but only 2 available
        let result = plan_cooperative_hunt([10, 1, 10], &members, 3, 20.0);
        assert!(result.is_none());
    }

    #[test]
    fn cooperative_hunt_succeeds_with_enough() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.8),
            make_member(3, [7, 1, 5], 0.6, 0.7),
        ];
        let result = plan_cooperative_hunt([10, 1, 10], &members, 2, 20.0);
        assert!(result.is_some());
        if let Some(GroupAction::CooperativeHunt { participants, .. }) = result {
            assert!(participants.len() >= 2);
        }
    }

    #[test]
    fn hunt_excludes_injured_members() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.1), // too injured
            make_member(3, [7, 1, 5], 0.6, 0.7),
        ];
        let result = plan_cooperative_hunt([10, 1, 10], &members, 3, 20.0);
        assert!(result.is_none()); // only 2 eligible
    }

    #[test]
    fn hunt_excludes_distant_members() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [100, 1, 100], 0.7, 0.8), // too far
            make_member(3, [7, 1, 5], 0.6, 0.7),
        ];
        let result = plan_cooperative_hunt([10, 1, 10], &members, 3, 20.0);
        assert!(result.is_none());
    }

    #[test]
    fn territory_defense_requires_owned_territory() {
        let mut registry = FactionRegistry::default();
        let faction = Faction::new(FactionId(1), "Pack");
        registry.add_faction(faction);

        let members = vec![make_member(1, [5, 1, 5], 0.8, 0.9)];
        // Chunk [0,0] is NOT claimed
        let result =
            plan_territory_defense([5, 1, 5], [0, 0], FactionId(1), &members, &registry, 3);
        assert!(result.is_none());
    }

    #[test]
    fn territory_defense_mobilizes_defenders() {
        let mut registry = FactionRegistry::default();
        let mut faction = Faction::new(FactionId(1), "Pack");
        faction.claim_territory([0, 0]);
        registry.add_faction(faction);

        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.8),
        ];
        let result =
            plan_territory_defense([8, 1, 8], [0, 0], FactionId(1), &members, &registry, 3);
        assert!(result.is_some());
        if let Some(GroupAction::TerritoryDefense { defenders, .. }) = result {
            assert_eq!(defenders.len(), 2);
        }
    }

    #[test]
    fn territory_defense_caps_at_max() {
        let mut registry = FactionRegistry::default();
        let mut faction = Faction::new(FactionId(1), "Pack");
        faction.claim_territory([0, 0]);
        registry.add_faction(faction);

        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.8),
            make_member(3, [7, 1, 5], 0.6, 0.7),
        ];
        let result =
            plan_territory_defense([8, 1, 8], [0, 0], FactionId(1), &members, &registry, 2);
        if let Some(GroupAction::TerritoryDefense { defenders, .. }) = result {
            assert_eq!(defenders.len(), 2);
        }
    }

    #[test]
    fn food_sharing_pairs_hungry_with_fed() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.9, 0.9),  // well-fed giver
            make_member(2, [6, 1, 5], 0.15, 0.8), // hungry receiver
        ];
        let result = plan_food_sharing(&members, 0.3, 5.0);
        assert!(result.is_some());
        if let Some(GroupAction::ShareFood { giver, receiver }) = result {
            assert_eq!(giver, CreatureId(1));
            assert_eq!(receiver, CreatureId(2));
        }
    }

    #[test]
    fn food_sharing_none_when_all_fed() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.9, 0.9),
            make_member(2, [6, 1, 5], 0.8, 0.8),
        ];
        let result = plan_food_sharing(&members, 0.3, 5.0);
        assert!(result.is_none());
    }

    #[test]
    fn food_sharing_none_when_out_of_range() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.9, 0.9),
            make_member(2, [100, 1, 100], 0.1, 0.8),
        ];
        let result = plan_food_sharing(&members, 0.3, 5.0);
        assert!(result.is_none());
    }

    #[test]
    fn rally_triggers_when_scattered() {
        let members = vec![
            make_member(1, [0, 1, 0], 0.8, 0.9),
            make_member(2, [50, 1, 50], 0.7, 0.8),
        ];
        let result = plan_rally([25, 1, 25], &members, 10.0);
        assert!(result.is_some());
        if let Some(GroupAction::Rally { participants, .. }) = result {
            assert_eq!(participants.len(), 2);
        }
    }

    #[test]
    fn rally_skips_when_close() {
        let members = vec![
            make_member(1, [5, 1, 5], 0.8, 0.9),
            make_member(2, [6, 1, 5], 0.7, 0.8),
        ];
        let result = plan_rally([5, 1, 5], &members, 10.0);
        assert!(result.is_none());
    }

    #[test]
    fn rally_empty_members_returns_none() {
        let result = plan_rally([0, 0, 0], &[], 5.0);
        assert!(result.is_none());
    }
}
