pub mod chunk;
pub mod chunk_manager;
pub mod collision;
pub mod interpolation;
pub mod lod;
pub mod meshing;
pub mod octree;
pub mod raycast;
pub mod refinement;
pub mod terrain;
pub mod voxel;
pub mod voxel_access;

use bevy::prelude::*;

use chunk_manager::ChunkManagerPlugin;
use meshing::MeshingPlugin;
use refinement::RefinementPlugin;

/// System set ordering for the world pipeline.
#[derive(SystemSet, Debug, Clone, PartialEq, Eq, Hash)]
pub enum WorldSet {
    /// Chunk loading/unloading.
    ChunkManagement,
    /// Mesh generation from voxel data.
    Meshing,
}

pub struct WorldPlugin;

impl Plugin for WorldPlugin {
    fn build(&self, app: &mut App) {
        app.configure_sets(Update, WorldSet::Meshing.after(WorldSet::ChunkManagement))
            .insert_resource(lod::LodConfig::default())
            .insert_resource(lod::MaterialColorMap::from_defaults())
            .add_plugins(ChunkManagerPlugin)
            .add_plugins(MeshingPlugin)
            .add_plugins(RefinementPlugin)
            .add_systems(Startup, setup_scene);
    }
}

/// Scene lighting. Terrain is now generated by the voxel pipeline.
fn setup_scene(mut commands: Commands) {
    // Directional light (sun)
    commands.spawn((
        DirectionalLight {
            illuminance: 10_000.0,
            shadows_enabled: true,
            ..default()
        },
        Transform::from_rotation(Quat::from_euler(EulerRot::XYZ, -0.8, 0.3, 0.0)),
    ));

    // Ambient light
    commands.spawn(AmbientLight {
        color: Color::WHITE,
        brightness: 200.0,
        ..default()
    });
}
