pub mod chunk;
pub mod chunk_manager;
pub mod meshing;
pub mod terrain;
pub mod voxel;

use bevy::prelude::*;

use chunk_manager::ChunkManagerPlugin;
use meshing::MeshingPlugin;

pub struct WorldPlugin;

impl Plugin for WorldPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(ChunkManagerPlugin)
            .add_plugins(MeshingPlugin)
            .add_systems(Startup, setup_scene);
    }
}

/// Scene lighting. Terrain is now generated by the voxel pipeline.
fn setup_scene(mut commands: Commands) {
    // Directional light (sun)
    commands.spawn((
        DirectionalLight {
            illuminance: 10_000.0,
            shadows_enabled: true,
            ..default()
        },
        Transform::from_rotation(Quat::from_euler(EulerRot::XYZ, -0.8, 0.3, 0.0)),
    ));

    // Ambient light
    commands.spawn(AmbientLight {
        color: Color::WHITE,
        brightness: 200.0,
        ..default()
    });
}
